### PR TITLE
Added Result view

### PR DESCRIPTION
**Pull request by mineofcode**
New Result view component Added

### CODE REVIEW

**Comment by masagatech** [comment]
image

image

image

image

**Comment by BeeMargarida** [comment]
Hum, this component is really specific, I'm not sure we want this component in specific. I'm gonna leave this parked while we discuss this

**Comment by masagatech** [comment]
> Hum, this component is really specific, I'm not sure we want this component in specific. I'm gonna leave this parked while we discuss this

It is very useful. One of my project I used this. You can show this on model for any operation status.

**Comment by Brisklemonade** [comment]
The code is very clean I like that. I feel as though this component is very niche though. What are some practical uses for it?

**Comment by masagatech** [comment]
> The code is very clean I like that. I feel as though this component is very niche though. What are some practical uses for it?

This is result component. When important operations need to inform the user to process the results and the feedback is more complicated. It's out of the box we are providing in toolbox.

**Comment by khalibloo** [comment]
AntD has a similar component https://ant.design/components/result?theme=dark
I think it's nice to have. But really, it's very easy to put this together from existing components, even without specifically making a component for it in the library.

**Comment by BeeMargarida** [comment]
I'm gonna close this for now, it's not a priority.

**Pull request closed without merging**
