### PR TITLE
[docs]: Added a search bar

### PR DESCRIPTION
**Pull request by Caladan08**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing guide](https://github.com/svelteuidev/svelteui/blob/main/CONTRIBUTING.md)
- [x] Prefix your PR title with `[@svelteui/core]`, `[@svelteui/actions]`, `[@svelteui/motion]`, `[@svelteui/core]`, `[core]`, or `[docs]`.
- [x] This message body should clearly illustrate what problems it solves.

### Tests

- [x] Run the tests with `npm test` and lint the project with `yarn lint` or just run `yarn repo:prepush` and check to see if it's passing.

Added a search bar which appears as an icon in the `TopBar`. There are few things which could be improved which I'm listing below but I have no idea how to do it:

- On opening the modal, the TextInput needs to auto-focus. But unfortunately, when I use the `TextInput` component, there is no way for me to bind the input field to a variable (as far as I know)
- When I navigate to a link, the appropriate sidebar section needs to be expanded and the link needs to be shown as active. I tried to achieve this, but `node.querySelectorAll('a')` in `link-actions.js` only returns the first five links (Introduction, Installation, Learn the Basics, Contributing, FAQ) even though console logging `node.querySelectorAll('a')` returns all the links in the sidebar.

### CODE REVIEW

**Comment by Brisklemonade** [comment]
I'm really digging this addition! Great work, I'll try to look into the sidebar expansion logic.

**Comment by Brisklemonade** [comment]
From a UI standpoint, do you think it would make more sense to have the search be an input rather than an icon on desktop?

**Comment by Caladan08** [comment]
Sure, that would look better! I'll try adding it. My discord is Caladan#6196

**Comment by Caladan08** [comment]
How does this look?

**Comment by Brisklemonade** [comment]
Looks great!

**Comment by Caladan08** [comment]
What's the status on this?

**Comment by Caladan08** [comment]
I'm having a few problems with this. One way we could do this is by using `fs` and then mapping all the files in the `/pages/` folder into an object. But since we can't use `fs` in any of the files, that method is not an option. If it was in SvelteKit, we could load in the files in `+layout.server.js`, put it in a store and use that store in the TopBar but currently, I'm not sure of any other way this could be done.

**Comment by BeeMargarida** [comment]
One small thing, would it be possible to rebase with next-minor? There are some extra commits here that should be not showing

**Comment by Caladan08** [comment]
I'm not really that great with git, so could you please tell how that is done?

**Comment by BeeMargarida** [comment]
> I'm not really that great with git, so could you please tell how that is done?

It seems like git merge with next-minor won't fix this, honestly I would have to search how to do it as well, since I have no idea. A rebase would be my first guess (but confusing), or a fresh start in another branch, which kinda sucks and gives you way more work.

**Comment by Caladan08** [comment]
I could rewrite the code starting from the new branch. It's not really that difficult of a work

**Comment by BeeMargarida** [comment]
> I could rewrite the code starting from the new branch. It's not really that difficult of a work. Shall I do it?
> 

That would be great, thank you!

**Comment by Caladan08** [comment]
Shall I close this PR and create a new one with the correct branch?

**Comment by Caladan08** [comment]
BTW, I just wanted to know, what is the status on switching the docs from `svelte-docs` to SvelteKit? Is it being actively worked on?

**Pull request closed without merging**
