### PR TITLE
[docs]: Migrated docs to Sveltekit

### PR DESCRIPTION
**Pull request by Caladan08**
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing guide](https://github.com/svelteuidev/svelteui/blob/main/CONTRIBUTING.md)
- [x] Prefix your PR title with `[@svelteui/core]`, `[@svelteui/actions]`, `[@svelteui/motion]`, `[@svelteui/core]`, `[core]`, or `[docs]`.
- [x] This message body should clearly illustrate what problems it solves.

### Tests

- [x] Run the tests with `npm test` and lint the project with `yarn lint` or just run `yarn repo:prepush` and check to see if it's passing.

This PR migrates the whole docs codebase to SvelteKit. It still needs a lot of work and the deployment would also probably have to be altered but I want to hear your thoughts on this

### CODE REVIEW

**Comment by BeeMargarida** [comment]
@Brisklemonade Pinging you, since you are also working on this in another branch

**Comment by BeeMargarida** [comment]
First of all, thank you so much for this PR, it looks like a lot of work and from a first look at the code, it looks good.
I'm of the opinion this could be done by steps, we could create a new branch for the new docs and this could be merged and then improved upon by small incremental steps. What do you think @Brisklemonade?

**Comment by BeeMargarida** [comment]
So, I'll go ahead and merge this against a branch for the migration of the docs to sveltekit. For now the objective is to maintain the same design and behaviour and just port it to sveltekit.
This can be merged now with problems, we can fix it in the branch moving forward and when it's ready we push to next-minor.
Thank you so much @Caladan08, could you resolve the conflicts to that it is merged?

**Comment by Caladan08** [comment]
Actually I don't even know what the conflicts are since here in Github, it is just showing that there are conflicts and that the conflicts are "too complex to resolve in the web editor"

**Comment by BeeMargarida** [comment]
Hum, I'll check it out

**Comment by BeeMargarida** [comment]
I hope you don't mind, I've fixed the conflicts on the branch. Could you make sure that nothing is broken after that? I checked and all seemed to work, but I want to make sure. After that I'll merge it and then we start by working on the current problems: (SSR is kinda broken due to the current limitation of svelteUI - a PR with a fix is ready, navigation, search, deployment, etc)

**Comment by Caladan08** [comment]
Yep, I've tried the code and everything works! Thanks

**Review by BeeMargarida — APPROVED** [review]

**Pull request merged**
